## Email Configuration
email.smtp.host=smtp.gmail.com
email.smtp.port=587
email.username=fida.boufares@gmail.com
email.password=wtgu dvpm kmbl gwho
email.smtp.auth=true
email.smtp.starttls.enable=true